install.packages('tidyverse')
BiocManager::install("clusterProfiler")
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("org.Hs.eg.db")
install.packages('pheatmap')
install.packages("DOSE")
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("enrichplot", force=TRUE)
install.packages("ggupset")
install.packages("genekitr")
install.packages("ggridges")
BiocManager::install(c("qvalue","GO.db"))
BiocManager::install("pathview")
install.packages("ggplot2")
install.packages("openxlsx")
BiocManager::install("BiocParallel", force=TRUE)
BiocManager::install("GSEA.barplot")
install.packages("wordcloud")
BiocManager::install("fgsea")
BiocManager::install("enrichTF")
BiocManager::install("msigdbr")
install.packages("ggpubr")

###############################################################################
library(msigdbr)
library(enrichTF )
library(wordcloud)
library(dplyr)
library(BiocManager)
library(BiocParallel)
library(ggridges)
library(DOSE)
library(ggridges)
library(genekitr)
library(clusterProfiler)
library(enrichplot)
library(ggplot2)
library(openxlsx)
library(dplyr)
library(stringr)
library(fgsea)
library(pathview)
library(ReactomePA)
library(edgeR)
library(DESeq2)
library(readxl)
library(pheatmap)
library(sm)
library(ComplexHeatmap)
library(RColorBrewer)
library(circlize)
library(ggrepel)
library(tidyverse) 
library(org.Hs.eg.db)
library(writexl)
library(generics)
library(ggpubr)
